### PR TITLE
added getters in command

### PR DESCRIPTION
**Pull request by rodrigorafaeldamaceno**
This pull request introduces getter methods to the Command class, enhancing the clarity and readability of state checks when used in views. By encapsulating the logic for determining command states (isIdle, isRunning, isCancelled, and isSuccess) into dedicated getters, the code becomes more concise and expressive.

These changes aim to improve the developer experience by providing a cleaner and more intuitive interface for interacting with Command objects, reducing boilerplate and improving maintainability. This enhancement is particularly beneficial when building user interfaces, as it simplifies state-driven UI updates and aligns with best practices for state management in Flutter applications.

### CODE REVIEW

**Review by wellgenio — CHANGES_REQUESTED** [review]
@rodrigorafaeldamaceno  add usage examples in the README and docs

**Comment by rodrigorafaeldamaceno** [comment]
@wellgenio I updated the examples in README and added isFailure getter

**Comment by wellgenio** [comment]
@rodrigorafaeldamaceno  keep the old README examples too and add the example comments:
```dart
/// Checks if the current command is running.
bool get isRunning => value is RuningCommand<T>;
````

**Comment by rodrigorafaeldamaceno** [comment]
@wellgenio I updated the README with a Getters section

**Pull request merged**
